### ISSUE TITLE
clickable-card throwing errors for nulled item

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#363]
On https://education.illinois.edu, there's the occasional error in dev tools dealing with clickable cards 
````
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at i.value (toolkit.js:24:26717)
    at i._$AE (toolkit.js:12:5298)
    at i.performUpdate (toolkit.js:12:5102)
    at i.scheduleUpdate (toolkit.js:12:4688)
    at i._$E_ (toolkit.js:12:4596)
````

**Comment by bryanjonker-illinois** [comment]
Validated that this is fixed - checking for nulled slots
